### ISSUE TITLE
output doesn't give swaped face image in stable diffusion faceswaplab 

### ISSUE THREAD

**Issue by ayush1268** [glucauze/sd-webui-faceswaplab#158]
hello sir/ mam recently i was started using faceswaplab in stable diffusion (automatic1111) in my pc to create an imaginary instagram model or ai model which would be completely imaginary but i can't be able to use this cause it doesn't  give me a good and consistent face in the output compared to the other's work i have also i have noticed when my image creation is completed in the cmd window it shows me this error which is as follows 

*** Error running postprocess_batch: F:\stable diffution\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "F:\stable diffution\stable-diffusion-webui\modules\scripts.py", line 659, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "F:\stable diffution\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 177, in postprocess_batch
        if self.enable:
           ^^^^^^^^^^^
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
*** Error running postprocess_image: F:\stable diffution\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "F:\stable diffution\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "F:\stable diffution\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
           ^^^^^^^^^^^
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
2023-12-02 15:24:39,826 - FaceSwapLab - ERROR - Failed to swap face in postprocess method : 'FaceSwapScript' object has no attribute 'units'
Traceback (most recent call last):
  File "F:\stable diffution\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py", line 170, in postprocess
    if self.enabled:
       ^^^^^^^^^^^^
  File "F:\stable diffution\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py", line 85, in enabled
    return any([u.enable for u in self.units]) and not shared.state.interrupted

i think this is some sort of errors or this is realated to my system specs  due to which i can't able to get a good and consistent image in the output or as a result i don't think this is realated to my system but still i will write my pc specs so if this could be helpfull more

pc specs :- intel i5 8th gen 
gpu - gtx 1050ti 4 gb 

i hope developer or someone will guide me at his best

**Comment by HAL9090** [comment]
I have the same problem! 

023-12-06 17:09:47,489 - FaceSwapLab - ERROR - Failed to swap face in postprocess method : 'FaceSwapScript' object has no attribute 'units'
Traceback (most recent call last):
  File "/home/sal9000/stable-diffusion-webui/extensions/sd-webui-faceswaplab/scripts/faceswaplab.py", line 170, in postprocess
    if self.enabled:
  File "/home/sal9000/stable-diffusion-webui/extensions/sd-webui-faceswaplab/scripts/faceswaplab.py", line 85, in enabled
    return any([u.enable for u in self.units]) and not shared.state.interrupted
AttributeError: 'FaceSwapScript' object has no attribute 'units'
*** Error running postprocess: /home/sal9000/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py
    Traceback (most recent call last):
      File "/home/sal9000/stable-diffusion-webui/modules/scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "/home/sal9000/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py", line 259, in postprocess
        if self.enable:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

I have deleted the plugin and installed it again. No function. It had worked perfectly before! Do you have a solution? 
I would be grateful for any help.

Hal9090
