### ISSUE TITLE
img2img not saving batch images into output directory

### ISSUE THREAD

**Issue by Xxredz** [glucauze/sd-webui-faceswaplab#187]
My batch of generated images is not saving in my output folder or in any folder.

To reproduce:

Go to img2img
Click the Batch tab
Add an input directory that contains your source image and an output directory
Activate FaceSwapLab to swap the source face
Click generate

Error: Not saving images.

How can I fix this?

**Comment by GunnyNinja** [comment]
For me img2img not saving ANY image to output folder.

**Comment by Vanglator** [comment]
I'm having the same issue, but it isn't saving in either img2img or text2img. I've tried using the default output location and a temporary one and neither are working. I can go in and manually save a single photo one at a time, but this isn't preferable when working with a batch of images.

**Comment by LucianoDaluz** [comment]
Same here, does anybody know how to fix it?

2024-06-03 11:53:01,725 - FaceSwapLab - ERROR - Failed to swap face in postprocess method : apply_overlay() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "C:\Users\lucia\Videos\SD\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py", line 201, in postprocess
    swp_img = imgutils.apply_mask(swp_img, p, batch_index)
  File "C:\Users\lucia\Videos\SD\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_utils\imgutils.py", line 224, in apply_mask
    img = processing.apply_overlay(img, p.paste_to, batch_index, p.overlay_images)
TypeError: apply_overlay() takes 3 positional arguments but 4 were given
