### ISSUE TITLE
Does not work on Automatic1111

### ISSUE THREAD

**Issue by nitinmukesh** [glucauze/sd-webui-faceswaplab#189]
**Describe the bug**
After installing the extension, the faceswaplab tab does not appear in Automatic1111. I installed fresh without any other plugins.

venv "C:\sd\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.0
Commit hash: adadb4e3c7382bf3e4f7519126cd6c70f4f8557b
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.007817600000635139
Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
```
*** Error loading script: faceswaplab.py
    Traceback (most recent call last):
      File "C:\sd\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\sd\stable-diffusion-webui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\sd\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py", line 10, in <module>
        from scripts.faceswaplab_api import faceswaplab_api
      File "C:\sd\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_api\faceswaplab_api.py", line 12, in <module>
        from scripts.faceswaplab_swapping import swapper
      File "C:\sd\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\swapper.py", line 14, in <module>
        import insightface
      File "C:\sd\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 18, in <module>
        from . import app
      File "C:\sd\stable-diffusion-webui\venv\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
        from .mask_renderer import *
      File "C:\sd\stable-diffusion-webui\venv\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
        import albumentations as A
      File "C:\sd\stable-diffusion-webui\venv\lib\site-packages\albumentations\__init__.py", line 3, in <module>
        from .augmentations import *
      File "C:\sd\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\__init__.py", line 1, in <module>
        from .blur.functional import *
      File "C:\sd\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\blur\__init__.py", line 1, in <module>
        from .functional import *
      File "C:\sd\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\blur\functional.py", line 9, in <module>
        from albumentations.augmentations.geometric.functional import scale
      File "C:\sd\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\geometric\__init__.py", line 2, in <module>
        from .resize import *
      File "C:\sd\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\geometric\resize.py", line 6, in <module>
        from pydantic import Field, ValidationInfo, field_validator
    ImportError: cannot import name 'ValidationInfo' from 'pydantic' (C:\sd\stable-diffusion-webui\venv\lib\site-packages\pydantic\__init__.cp310-win_amd64.pyd)
```

---
Loading weights [6ce0161689] from C:\sd\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\sd\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 26.0s (prepare environment: 9.6s, import torch: 5.5s, import gradio: 2.1s, setup paths: 4.1s, initialize shared: 0.4s, other imports: 2.1s, load scripts: 1.5s, create ui: 0.4s, gradio launch: 0.3s).
Applying attention optimization: Doggettx... done.
Model loaded in 6.4s (load weights from disk: 0.4s, create model: 0.4s, apply weights to model: 5.0s, apply dtype to VAE: 0.3s, calculate empty prompt: 0.2s).

**To Reproduce**
Install the extension and launch Automatic1111.

**Expected behavior**
The faceswaplab extension should appear in Automatic1111 Webui.

**Screenshots**
N.A.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] N. A.

**Comment by nitinmukesh** [comment]
>pip list

Package                   Version
------------------------- ------------
accelerate                0.21.0
aenum                     3.1.15
aiofiles                  23.2.1
aiohttp                   3.9.5
aiosignal                 1.3.1
albumentations            1.4.4
altair                    5.3.0
annotated-types           0.6.0
antlr4-python3-runtime    4.9.3
anyio                     3.7.1
async-timeout             4.0.3
attrs                     23.2.0
blendmodes                2022
certifi                   2024.2.2
charset-normalizer        3.3.2
clean-fid                 0.1.35
click                     8.1.7
clip                      1.0
colorama                  0.4.6
coloredlogs               15.0.1
contourpy                 1.2.1
cycler                    0.12.1
Cython                    3.0.10
deprecation               2.1.0
diskcache                 5.6.3
easydict                  1.13
einops                    0.4.1
exceptiongroup            1.2.0
facexlib                  0.3.0
fastapi                   0.94.0
ffmpy                     0.3.2
filelock                  3.13.4
filterpy                  1.4.5
flatbuffers               24.3.25
fonttools                 4.51.0
frozenlist                1.4.1
fsspec                    2024.3.1
ftfy                      6.2.0
gitdb                     4.0.11
GitPython                 3.1.32
gradio                    3.41.2
gradio_client             0.5.0
h11                       0.12.0
httpcore                  0.15.0
httpx                     0.24.1
huggingface-hub           0.22.2
humanfriendly             10.0
idna                      3.7
ifnude                    0.0.3
imageio                   2.34.0
importlib_resources       6.4.0
inflection                0.5.1
insightface               0.7.3
Jinja2                    3.1.3
joblib                    1.4.0
jsonmerge                 1.8.0
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
kornia                    0.6.7
lark                      1.1.2
lazy_loader               0.4
lightning-utilities       0.11.2
llvmlite                  0.42.0
MarkupSafe                2.1.5
matplotlib                3.8.4
mpmath                    1.3.0
multidict                 6.0.5
networkx                  3.3
numba                     0.59.1
numpy                     1.26.2
omegaconf                 2.2.3
onnx                      1.16.0
onnxruntime               1.17.3
onnxruntime-gpu           1.17.1
open-clip-torch           2.20.0
opencv-python             4.9.0.80
opencv-python-headless    4.9.0.80
orjson                    3.10.1
packaging                 24.0
pandas                    2.2.2
piexif                    1.1.3
Pillow                    9.5.0
pip                       22.2.1
prettytable               3.10.0
protobuf                  3.20.3
psutil                    5.9.5
pydantic                  1.10.15
pydantic_core             2.18.1
pydub                     0.25.1
pyparsing                 3.1.2
pyreadline3               3.4.1
python-dateutil           2.9.0.post0
python-multipart          0.0.9
pytorch-lightning         1.9.4
pytz                      2024.1
PyWavelets                1.6.0
PyYAML                    6.0.1
referencing               0.34.0
regex                     2024.4.16
requests                  2.31.0
resize-right              0.0.2
rpds-py                   0.18.0
safetensors               0.4.2
scikit-image              0.21.0
scikit-learn              1.4.2
scipy                     1.13.0
semantic-version          2.10.0
sentencepiece             0.2.0
setuptools                63.2.0
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
spandrel                  0.1.6
starlette                 0.26.1
sympy                     1.12
threadpoolctl             3.4.0
tifffile                  2024.4.18
timm                      0.9.16
tokenizers                0.13.3
tomesd                    0.1.3
toolz                     0.12.1
torch                     2.1.2+cu121
torchdiffeq               0.2.3
torchmetrics              1.3.2
torchsde                  0.2.6
torchvision               0.16.2+cu121
tqdm                      4.66.2
trampoline                0.1.2
transformers              4.30.2
typing_extensions         4.11.0
tzdata                    2024.1
urllib3                   2.2.1
uvicorn                   0.29.0
wcwidth                   0.2.13
websockets                11.0.3
yarl                      1.9.4

**Comment by SkGirlUru** [comment]
the same happens to me

**Comment by henrikmk** [comment]
For what it's worth, the fix that works for me is taken from the automatic1111 fix:

First go to the automatic1111 root directory. Then:

Powershell:

```
.\venv\Scripts\Activate.ps1
pip install albumentations==1.4.3
pip install pydantic==1.10.15
```
Cmd:

```
venv\Scripts\activate
pip install albumentations==1.4.3
pip install pydantic==1.10.15
```

Linux:

```
source venv/bin/activate
pip install albumentations==1.4.3
pip install pydantic==1.10.15
```

Source:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15564

Make sure to be on the latest PIP version.

**Comment by w-e-w** [comment]
- https://github.com/glucauze/sd-webui-faceswaplab/pull/190

**Comment by NeihTzxc** [comment]
> albumentations

it work for me. thanks.

**Comment by songib** [comment]
I'm on AMD side, and trying the solution it didn't work atm.

**Comment by anthonyalayo** [comment]
> Linux:
> 
> ```
> source venv/bin/activate
> pip install albumentations==1.4.3
> pip install pydantic==1.10.15
> ```

Worked for me, thanks!
