### ISSUE TITLE
Extension doesnt work on Webforge anymore for 2 days now

### ISSUE THREAD

**Issue by vixenius** [glucauze/sd-webui-faceswaplab#194]
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 2), reused 10 (delta 2), pack-reused 0
Unpacking objects: 100% (10/10), 2.56 KiB | 5.00 KiB/s, done.
From https://github.com/lllyasviel/stable-diffusion-webui-forge
   e6e18f7e..9cb69baf  main       -> origin/main
Updating e6e18f7e..9cb69baf
Fast-forward
 backend/attention.py          | 51 +++++++++++++++++++++++++++++++++++++++++++
 backend/state_dict.py         | 28 ++++++++++++++++++++++++
 backend/vae/configs/guess.py  |  9 ++++++++
 backend/vae/configs/sd15.json | 28 ++++++++++++++++++++++++
 backend/vae/loader.py         | 33 ++++++++++++++++++++++++++++
 5 files changed, 149 insertions(+)
 create mode 100644 backend/state_dict.py
 create mode 100644 backend/vae/configs/guess.py
 create mode 100644 backend/vae/configs/sd15.json
 create mode 100644 backend/vae/loader.py
venv "D:/AINOVO/stable-diffusion-webui/venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f1.0.2v1.10.1-previous-40-g9cb69baf
Commit hash: 9cb69baf9fcd0ac2847790555fc8ab603794f1b2
Total VRAM 11264 MB, total RAM 32690 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1080 Ti : native
VAE dtype: torch.float32
Installing requirements for Face Editor
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
Install protobuf>=3.20.2
Installing sd-webui-faceswaplab requirement: protobuf>=3.20.2
2.8542265000141924
CUDA 12.1
Launching Web UI with arguments: --xformers --ckpt-dir D:/AINOVO/stable-diffusion-webui/models/Stable-diffusion --hypernetwork-dir D:/AINOVO/stable-diffusion-webui/models/hypernetworks --embeddings-dir D:/AINOVO/stable-diffusion-webui/embeddings --lora-dir D:/AINOVO/stable-diffusion-webui/models/Lora --controlnet-dir D:/AINOVO/stable-diffusion-webui/extensions/sd-webui-controlnet/models
Total VRAM 11264 MB, total RAM 32690 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1080 Ti : native
VAE dtype: torch.float32
CUDA Stream Activated:  False
Using xformers cross attention
ControlNet preprocessor location: D:\AINOVO\WebForge\webui\models\ControlNetPreprocessor
CHv1.8.10: Get Custom Model Folder
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.6.0, num models: 41
10:12:00 - ReActor - STATUS - Running v0.7.1-a1 on Device: CUDA
Loading weights [3c5d7960a7] from D:\AINOVO\stable-diffusion-webui\models\Stable-diffusion\analogMadness_v70.safetensors
CHv1.8.10: Set Proxy:
model_type EPS
UNet ADM Dimension 0
*** Error calling: D:\AINOVO\WebForge\webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py/ui
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py", line 109, in ui
        components += faceswaplab_unit_ui.faceswap_unit_ui(is_img2img, i)
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_unit_ui.py", line 115, in faceswap_unit_ui
        batch_files = gr.components.File(
      File "D:\AINOVO\WebForge\webui\modules\gradio_extensions.py", line 126, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "D:\AINOVO\stable-diffusion-webui\venv\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "D:\AINOVO\stable-diffusion-webui\venv\lib\site-packages\gradio\components\file.py", line 98, in __init__
        raise ValueError(
    ValueError: Invalid value for parameter `type`: file. Please choose from one of: ['filepath', 'binary']

---
*** Error calling: D:\AINOVO\WebForge\webui\extensions\StylePile\scripts\StylePile.py/ui
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "D:\AINOVO\WebForge\webui\extensions\StylePile\scripts\StylePile.py", line 412, in ui
        gr.Gallery(value=ResultDirectionImages, show_label=False).style(
    AttributeError: 'Gallery' object has no attribute 'style'

---
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
*** Error calling: D:\AINOVO\WebForge\webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py/ui
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py", line 109, in ui
        components += faceswaplab_unit_ui.faceswap_unit_ui(is_img2img, i)
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_unit_ui.py", line 115, in faceswap_unit_ui
        batch_files = gr.components.File(
      File "D:\AINOVO\WebForge\webui\modules\gradio_extensions.py", line 126, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "D:\AINOVO\stable-diffusion-webui\venv\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "D:\AINOVO\stable-diffusion-webui\venv\lib\site-packages\gradio\components\file.py", line 98, in __init__
        raise ValueError(
    ValueError: Invalid value for parameter `type`: file. Please choose from one of: ['filepath', 'binary']

---
2024-07-30 10:12:02,468 - ControlNet - INFO - ControlNet UI callback registered.
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['alphas_cumprod', 'alphas_cumprod_prev', 'betas', 'log_one_minus_alphas_cumprod', 'posterior_log_variance_clipped', 'posterior_mean_coef1', 'posterior_mean_coef2', 'posterior_variance', 'sqrt_alphas_cumprod', 'sqrt_one_minus_alphas_cumprod', 'sqrt_recip_alphas_cumprod', 'sqrt_recipm1_alphas_cumprod'])
*** Error calling: D:\AINOVO\WebForge\webui\extensions\StylePile\scripts\StylePile.py/ui
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "D:\AINOVO\WebForge\webui\extensions\StylePile\scripts\StylePile.py", line 412, in ui
        gr.Gallery(value=ResultDirectionImages, show_label=False).style(
    AttributeError: 'Gallery' object has no attribute 'style'

---
To load target model SD1ClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  10039.2919921875
[Memory Management] Model Memory (MB) =  454.2076225280762
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  8561.084369659424
Moving model(s) has taken 0.31 seconds
*** Error executing callback ui_tabs_callback for D:\AINOVO\WebForge\webui\extensions\openpose-editor\scripts\main.py
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "D:\AINOVO\WebForge\webui\extensions\openpose-editor\scripts\main.py", line 75, in on_ui_tabs
        png_input = gr.UploadButton(label="Detect from Image", file_types=["image"], type="bytes", elem_id="openpose_detect_button")
      File "D:\AINOVO\WebForge\webui\modules\gradio_extensions.py", line 126, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "D:\AINOVO\stable-diffusion-webui\venv\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "D:\AINOVO\stable-diffusion-webui\venv\lib\site-packages\gradio\components\upload_button.py", line 82, in __init__
        raise ValueError(
    ValueError: Invalid value for parameter `type`: bytes. Please choose from one of: ['filepath', 'binary']

---
*** Error executing callback ui_tabs_callback for D:\AINOVO\WebForge\webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py
    Traceback (most recent call last):
      File "D:\AINOVO\WebForge\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_tab.py", line 424, in on_ui_tabs
        tools_ui()
      File "D:\AINOVO\WebForge\webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_tab.py", line 251, in tools_ui
        build_batch_files = gr.components.File(
      File "D:\AINOVO\WebForge\webui\modules\gradio_extensions.py", line 126, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "D:\AINOVO\stable-diffusion-webui\venv\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "D:\AINOVO\stable-diffusion-webui\venv\lib\site-packages\gradio\components\file.py", line 98, in __init__
        raise ValueError(
    ValueError: Invalid value for parameter `type`: file. Please choose from one of: ['filepath', 'binary']

---
Model loaded in 4.8s (load weights from disk: 0.1s, forge load real models: 1.9s, load VAE: 0.3s, load textual inversion embeddings: 1.5s, calculate empty prompt: 0.9s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 41.1s (prepare environment: 17.5s, launcher: 2.0s, import torch: 3.7s, setup paths: 0.6s, initialize shared: 0.1s, other imports: 0.5s, list SD models: 0.4s, load scripts: 5.0s, create ui: 7.6s, gradio launch: 3.6s).
![faceswaplab](https://github.com/user-attachments/assets/e10741da-dbb3-41b4-904b-d94afeea8595)

**Comment by mcdullmedia** [comment]
I confirm. thanks.

**Comment by Arkuda** [comment]
bump

**Comment by SencneS** [comment]
I've tried a few things to get it to work, nothing in the long history has helped. It's just stopped working.

**Comment by vixenius** [comment]
Hey I managed to fix it somehow following the guide i found online but cant find it in my browsing history. I uploaded my sd-faceswaplab folder to Google drive so you can downnload it and replace yours. 

https://drive.google.com/drive/folders/1XzbLXe2mCkktFlWCXD2Gv9u17MIrkFYq?usp=sharing

Folder goes into WebForge\webui\extensions folder. Lemme know if it works for you.

**Comment by SencneS** [comment]
> Hey I managed to fix it somehow following the guide i found online but cant find it in my browsing history. I uploaded my sd-faceswaplab folder to Google drive so you can downnload it and replace yours.
> 
> https://drive.google.com/drive/folders/1XzbLXe2mCkktFlWCXD2Gv9u17MIrkFYq?usp=sharing
> 
> Folder goes into WebForge\webui\extensions folder. Lemme know if it works for you.

I looked up the differences between the yours and mine, there was just a few files that had differences. Mostly cache.
Line 116 on "faceswaplab_unit_ui.py"
You placed ---- type="file",
With ---- type="filepath",
This was the only change I made - and the interface is back.
I have not tested anything out though, but the interface is back.
![image](https://github.com/user-attachments/assets/97620ffc-a7c2-469b-9188-08c24b8822c0)

**Comment by SencneS** [comment]
I figured I'd also check the other files just in case.
These are in the ".\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\" folder.

"faceswaplab_unit_ui.py"
Line 116 = type="filepath",

"faceswaplab_tab.py"
Line 252 = type="filepath",
Line 313 = type="filepath",
Line 369 = type="filepath",

**Comment by vixenius** [comment]
> I figured I'd also check the other files just in case. These are in the ".\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui" folder.
> 
> "faceswaplab_unit_ui.py" Line 116 = type="filepath",
> 
> "faceswaplab_tab.py" Line 252 = type="filepath", Line 313 = type="filepath", Line 369 = type="filepath",

Glad you fixed it my makka and gl to others as well.
