### ISSUE TITLE
txt2img not working only blend face img2img

### ISSUE THREAD

**Issue by argn1** [glucauze/sd-webui-faceswaplab#195]
**Describe the bug**
Not working in Automatic1111, had it working fine for txt2img then attempted to get the img2img working and now getting errors, can now only do blend face in img2img

**To Reproduce**
Fresh install of swapfacelab then click generate

**Expected behavior**
a face swap

**Screenshots**
Model loaded in 3.8s (load weights from disk: 0.4s, create model: 0.3s, apply weights to model: 2.8s, calculate empty prompt: 0.1s).
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:10<00:00,  2.93it/s]
2024-08-06 22:33:32,643 - FaceSwapLab - INFO - Try to use model : E:\SDTemp\stable-diffusion-webui\models\faceswaplab\inswapper_128.onnx
2024-08-06 22:33:32,648 - FaceSwapLab - INFO - Load analysis model det_size=(640, 640), det_thresh=0.5, providers = ['CPUExecutionProvider'], will take some time. (> 30s)
Loading (640, 640) analysis model (first time is slow): 100%|█████████████████████████| 1/1 [00:00<00:00,  1.35model/s]
2024-08-06 22:33:33,389 - FaceSwapLab - INFO - ("Applied providers: ['CPUExecutionProvider'], with options: "
 "{'CPUExecutionProvider': {}}\n"
 'find model: '
 'E:\\SDTemp\\stable-diffusion-webui\\models\\faceswaplab\\analysers\\models\\buffalo_l\\1k3d68.onnx '
 "landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0\n"
 "Applied providers: ['CPUExecutionProvider'], with options: "
 "{'CPUExecutionProvider': {}}\n"
 'find model: '
 'E:\\SDTemp\\stable-diffusion-webui\\models\\faceswaplab\\analysers\\models\\buffalo_l\\2d106det.onnx '
 "landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0\n"
 "Applied providers: ['CPUExecutionProvider'], with options: "
 "{'CPUExecutionProvider': {}}\n"
 'find model: '
 'E:\\SDTemp\\stable-diffusion-webui\\models\\faceswaplab\\analysers\\models\\buffalo_l\\det_10g.onnx '
 "detection [1, 3, '?', '?'] 127.5 128.0\n"
 "Applied providers: ['CPUExecutionProvider'], with options: "
 "{'CPUExecutionProvider': {}}\n"
 'find model: '
 'E:\\SDTemp\\stable-diffusion-webui\\models\\faceswaplab\\analysers\\models\\buffalo_l\\genderage.onnx '
 "genderage ['None', 3, 96, 96] 0.0 1.0\n"
 "Applied providers: ['CPUExecutionProvider'], with options: "
 "{'CPUExecutionProvider': {}}\n"
 'find model: '
 'E:\\SDTemp\\stable-diffusion-webui\\models\\faceswaplab\\analysers\\models\\buffalo_l\\w600k_r50.onnx '
 "recognition ['None', 3, 112, 112] 127.5 127.5\n"
 'set det-size: (640, 640)\n')
E:\SDTemp\stable-diffusion-webui\venv\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
2024-08-06 22:33:33,511 - FaceSwapLab - INFO - blend all faces together
2024-08-06 22:33:33,555 - FaceSwapLab - INFO - Load analysis model det_size=(320, 320), det_thresh=0.5, providers = ['CPUExecutionProvider'], will take some time. (> 30s)
Loading (320, 320) analysis model (first time is slow): 100%|█████████████████████████| 1/1 [00:00<00:00,  1.37model/s]
2024-08-06 22:33:34,287 - FaceSwapLab - INFO - ("Applied providers: ['CPUExecutionProvider'], with options: "
 "{'CPUExecutionProvider': {}}\n"
 'find model: '
 'E:\\SDTemp\\stable-diffusion-webui\\models\\faceswaplab\\analysers\\models\\buffalo_l\\1k3d68.onnx '
 "landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0\n"
 "Applied providers: ['CPUExecutionProvider'], with options: "
 "{'CPUExecutionProvider': {}}\n"
 'find model: '
 'E:\\SDTemp\\stable-diffusion-webui\\models\\faceswaplab\\analysers\\models\\buffalo_l\\2d106det.onnx '
 "landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0\n"
 "Applied providers: ['CPUExecutionProvider'], with options: "
 "{'CPUExecutionProvider': {}}\n"
 'find model: '
 'E:\\SDTemp\\stable-diffusion-webui\\models\\faceswaplab\\analysers\\models\\buffalo_l\\det_10g.onnx '
 "detection [1, 3, '?', '?'] 127.5 128.0\n"
 "Applied providers: ['CPUExecutionProvider'], with options: "
 "{'CPUExecutionProvider': {}}\n"
 'find model: '
 'E:\\SDTemp\\stable-diffusion-webui\\models\\faceswaplab\\analysers\\models\\buffalo_l\\genderage.onnx '
 "genderage ['None', 3, 96, 96] 0.0 1.0\n"
 "Applied providers: ['CPUExecutionProvider'], with options: "
 "{'CPUExecutionProvider': {}}\n"
 'find model: '
 'E:\\SDTemp\\stable-diffusion-webui\\models\\faceswaplab\\analysers\\models\\buffalo_l\\w600k_r50.onnx '
 "recognition ['None', 3, 112, 112] 127.5 127.5\n"
 'set det-size: (320, 320)\n')
2024-08-06 22:33:34,352 - FaceSwapLab - INFO - Int Gender : 0
2024-08-06 22:33:34,352 - FaceSwapLab - INFO - Process face 0
2024-08-06 22:33:34,356 - FaceSwapLab - INFO - Source Gender 0
Loading swap model: 100%|█████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/model]
2024-08-06 22:33:36,523 - FaceSwapLab - INFO - ("Applied providers: ['CPUExecutionProvider'], with options: "
 "{'CPUExecutionProvider': {}}\n"
 'inswapper-shape: [1, 3, 128, 128]\n')
2024-08-06 22:33:36,523 - FaceSwapLab - INFO - Target faces count : 1
2024-08-06 22:33:36,523 - FaceSwapLab - INFO - swap face 0
2024-08-06 22:33:36,841 - FaceSwapLab - INFO - ********************************************************************************
2024-08-06 22:33:36,841 - FaceSwapLab - INFO - Inswapper
2024-08-06 22:33:36,842 - FaceSwapLab - INFO - ********************************************************************************
2024-08-06 22:33:37,012 - FaceSwapLab - INFO - blend all faces together
2024-08-06 22:33:37,012 - FaceSwapLab - ERROR - You need at least one reference face
2024-08-06 22:33:37,012 - FaceSwapLab - ERROR - Failed to swap face in postprocess method : No reference face found
Traceback (most recent call last):
  File "E:\SDTemp\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py", line 187, in postprocess
    swapped_images = swapper.process_images_units(
  File "E:\SDTemp\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\swapper.py", line 843, in process_images_units
    nexts = process_images_units(model, units[1:], swapped, force_blend)
  File "E:\SDTemp\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\swapper.py", line 841, in process_images_units
    swapped = process_image_unit(model, units[0], image, info, force_blend)
  File "E:\SDTemp\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\swapper.py", line 723, in process_image_unit
    src_faces = [unit.blended_faces]
  File "E:\SDTemp\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_unit_settings.py", line 187, in blended_faces
    self._blended_faces = swapper.blend_faces(self.faces)
  File "E:\SDTemp\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_unit_settings.py", line 166, in faces
    [self.reference_face] if self.reference_face is not None else []
  File "E:\SDTemp\stable-diffusion-webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_unit_settings.py", line 154, in reference_face
    raise Exception("No reference face found")
Exception: No reference face found
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:14<00:00,  2.09it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:14<00:00,  3.03it/s]

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: chrome
 - Version 127.0.6533.89

**Comment by argn1** [comment]
I'm an idiot, I tried to save settings of swapfacelab to be the same on start up in automatic1111 and it saved the same settings of face1 to Face 2 and Face 3 also (which I've never touch) 
Also it doesn't save settings on Global Post-Processing tab
