### ISSUE TITLE
Not working with the newer version of Stable Diffusion Forge

### ISSUE THREAD

**Issue by kriimakt** [glucauze/sd-webui-faceswaplab#197]
Mostly due to Gradio deprecated options (mostly Placeholder and file type) the extension doesn't work with Stable Diffusion Forge.

I managed, with my limited knowledge, to make it work with SDXL models, by changing "file" to "filepath". There still are many errors, but it works, most of the time. 

When I try with Flux AI models, I only get a black square where the face is though. Any clue about how to fix this ? :)

**Comment by kriimakt** [comment]
I tried again, actually, everything works, except for auto inpainting after face swap. Can do it manually in img2img tab, but it doesn't work in extension :)

**Comment by Phantoxium** [comment]
I just transferred to Forge coming from A1111, where FaceSwapLab is working perfectly. However, I cannot get it installed properly in Forge. When I click on the arrow for FaceSwapLab in Txt2img or Img2img, the extension will not open up. I get the following error messages:

```
G:\Forge\webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_unit_ui.py:115: GradioDeprecationWarning: unexpected argument for File: optional
  batch_files = gr.components.File(
*** Error calling: G:\Forge\webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py/ui
    Traceback (most recent call last):
      File "G:\Forge\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "G:\Forge\webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py", line 109, in ui
        components += faceswaplab_unit_ui.faceswap_unit_ui(is_img2img, i)
      File "G:\Forge\webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_unit_ui.py", line 115, in faceswap_unit_ui
        batch_files = gr.components.File(
      File "G:\Forge\webui\modules\gradio_extensions.py", line 147, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "G:\Forge\system\python\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "G:\Forge\system\python\lib\site-packages\gradio\components\file.py", line 98, in __init__
        raise ValueError(
    ValueError: Invalid value for parameter `type`: file. Please choose from one of: ['filepath', 'binary']
```

Any clue what the problem is and how to fix it?

**Comment by kriimakt** [comment]
You can fix it by looking for all the type="file" occurences in the extension scripts, and replacing them with type="filepath". There will be other errors, but most of the extension will work, except for inpainting. Can't help much for the rest, my Python skills are limited  Considering the author hasn't worked on the extension for a year now, I guess it's your best course of action.

**Comment by GunnyNinja** [comment]
> You can fix it by looking for all the type="file" occurences in the extension scripts, and replacing them with type="filepath". There will be other errors, but most of the extension will work, except for inpainting. Can't help much for the rest, my Python skills are limited Considering the author hasn't worked on the extension for a year now, I guess it's your best course of action.

Can you specify the files you altered? Or even better, create a fork with your changes?

**Comment by Phantoxium** [comment]
@kriimakt: Thank you very much for your help! After reading your 1st post, I was not sure if we even had the same problem and which files exactly to change.

@GunnyNinja: You need to change the py-files in the sub-folders of "webui\extensions\sd-webui-faceswaplab\scripts". It's definitely "webui\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_unit_ui.py" and 1 or 2 others. Just open them in an editor, search for "type="file"", and replace with "type="filepath"". It will take you just a few minutes... There will be new error messages appearing, just like @kriimakt pointed out, but it works for me as well now. At least in Txt2img, I have not tested every function yet....

**Comment by kriimakt** [comment]
You can also try ReActor, another similar extension for A1111, it works fine with Forge. I prefer Faceswaplabs, but at least ReActor works 100%.

**Comment by Musigreg** [comment]
I tried Kriimakt methods and it gives me a whole other pack of errors.
After that, no faceswap, and no saving the image either. It's stuck as a tmp file and doesn't produce the png.

Edit : I didn't have an upscaler selected... No issue.

**Comment by jandrop** [comment]
This fork works for me https://github.com/Ethereum-John/sd-webui-forge-faceswaplab

**Comment by GunnyNinja** [comment]
> This fork works for me https://github.com/Ethereum-John/sd-webui-forge-faceswaplab

It works the same as one of the other forks I found, but just like with A1111, it does not output img2img to the folder.

**Comment by LucianoDaluz** [comment]
> > This fork works for me https://github.com/Ethereum-John/sd-webui-forge-faceswaplab
> 
> It works the same as one of the other forks I found, but just like with A1111, it does not output img2img to the folder.

It work with Flux as well, but Flux for people are not good. Thanks!

**Comment by coolguy001tv** [comment]
> > This fork works for me https://github.com/Ethereum-John/sd-webui-forge-faceswaplab
> 
> It works the same as one of the other forks I found, but just like with A1111, it does not output img2img to the folder.
it seems that  Ethereum-John/sd-webui-forge-faceswaplab isn't downloadable anymore, can anyone offer a zip file or something?

**Comment by jewelsonn** [comment]
> > > This fork works for me https://github.com/Ethereum-John/sd-webui-forge-faceswaplab
> > 
> > 
> > It works the same as one of the other forks I found, but just like with A1111, it does not output img2img to the folder.
> > it seems that  Ethereum-John/sd-webui-forge-faceswaplab isn't downloadable anymore, can anyone offer a zip file or something?

I have a fork https://github.com/jewelsonn/sd-webui-faceswaplab.git and It works

**Comment by coolguy001tv** [comment]
> > > > This fork works for me https://github.com/Ethereum-John/sd-webui-forge-faceswaplab
> > > 
> > > 
> > > It works the same as one of the other forks I found, but just like with A1111, it does not output img2img to the folder.
> > > it seems that  Ethereum-John/sd-webui-forge-faceswaplab isn't downloadable anymore, can anyone offer a zip file or something?
> 
> I have a fork https://github.com/jewelsonn/sd-webui-faceswaplab.git and It works

thanks, after add some files such as inswapper_128.onnx and parsing_parsenet.pth  from A1111's such extension, I managed to run this in forge.

**Comment by subtlecaffeine** [comment]
Check your gradio versions:

`python: 3.10.16  •  torch: 2.1.2+cu121  •  xformers: 0.0.23.post1  •  gradio: 3.41.2`

The fork mentioned here with the `filepath` changes don't work on my install; which is only a couple of days old.
