### ISSUE TITLE
A1111 Directml AMD GPU - upscale in FSL stopped working after the git pull/update of the extensions

### ISSUE THREAD

**Issue by Voidbord** [glucauze/sd-webui-faceswaplab#198]
Hey,
so yesterday I git pulled the A1111 Directml build together with updating extensions. Since then, FaceSwap Lab **face upscale** is not working with any of the upscale. I tried to git clone the A1111 repo, build venv from a scratch and get FaceSwap Lab repo as the one and only extension. It didn't help and the faceswap lab generates the following problem when using an upscale:

2024-09-04 21:54:20,554 - FaceSwapLab - INFO - Try to use model : C:\Users\mbord_\Documents\stable-diffusion-webui-directml\models\faceswaplab\inswapper_128.onnx
2024-09-04 21:54:20,872 - FaceSwapLab - INFO - blend all faces together
2024-09-04 21:54:20,872 - FaceSwapLab - INFO - loading face DEFAN_FULL.safetensors
2024-09-04 21:54:20,874 - FaceSwapLab - INFO - Int Gender : 0
2024-09-04 21:54:20,874 - FaceSwapLab - INFO - Process face 0
2024-09-04 21:54:20,884 - FaceSwapLab - INFO - Source Gender 0
2024-09-04 21:54:20,885 - FaceSwapLab - INFO - Target faces count : 1
2024-09-04 21:54:20,885 - FaceSwapLab - INFO - swap face 0
2024-09-04 21:54:21,681 - FaceSwapLab - INFO - ********************************************************************************
2024-09-04 21:54:21,681 - FaceSwapLab - INFO - Inswapper
2024-09-04 21:54:21,683 - FaceSwapLab - INFO - Upscale with ESRGAN_4x scale = 4
tiled upscale:   0%|                                                                             | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\upscaled_inswapper.py", line 215, in get
    bgr_fake = self.upscale_and_restore(
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\upscaled_inswapper.py", line 153, in upscale_and_restore
    upscaled = upscaling.upscale_img(pil_img, pp_options)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions\sd-webui-faceswaplab\scripts\faceswaplab_postprocessing\upscaling.py", line 19, in upscale_img
    result_image = pp_options.upscaler.scaler.upscale(
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\upscaler.py", line 68, in upscale
    img = self.do_upscale(img, selected_model)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\esrgan_model.py", line 36, in do_upscale
    return esrgan_upscale(model, img)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\esrgan_model.py", line 57, in esrgan_upscale
    return upscale_with_model(
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\upscaler_utils.py", line 74, in upscale_with_model
    output = upscale_pil_patch(model, tile)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\upscaler_utils.py", line 48, in upscale_pil_patch
    return torch_bgr_to_pil_image(model(tensor))
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\spandrel\__helpers\model_descriptor.py", line 472, in __call__
    output = self._call_fn(self.model, image)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\spandrel\__helpers\model_descriptor.py", line 439, in <lambda>
    self._call_fn = call_fn or (lambda model, image: model(image))
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\spandrel\architectures\ESRGAN\arch\RRDB.py", line 142, in forward
    return self.model(x)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions-builtin\Lora\networks.py", line 599, in network_Conv2d_forward
    return originals.Conv2d_forward(self, input)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\dml\amp\autocast_mode.py", line 43, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: forward(op, args, kwargs))
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\dml\amp\autocast_mode.py", line 15, in forward
    return op(*args, **kwargs)
RuntimeError: Cannot set version_counter for inference tensor
2024-09-04 21:54:21,948 - FaceSwapLab - ERROR - Conversion failed Cannot set version_counter for inference tensor
2024-09-04 21:54:21,948 - FaceSwapLab - ERROR - Failed to swap face in postprocess method : Cannot set version_counter for inference tensor
Traceback (most recent call last):
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py", line 187, in postprocess
    swapped_images = swapper.process_images_units(
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\swapper.py", line 841, in process_images_units
    swapped = process_image_unit(model, units[0], image, info, force_blend)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\swapper.py", line 752, in process_image_unit
    result: ImageResult = swap_face(
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\swapper.py", line 658, in swap_face
    raise e
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\swapper.py", line 646, in swap_face
    result = face_swapper.get(
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\upscaled_inswapper.py", line 328, in get
    raise e
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\upscaled_inswapper.py", line 215, in get
    bgr_fake = self.upscale_and_restore(
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions\sd-webui-faceswaplab\scripts\faceswaplab_swapping\upscaled_inswapper.py", line 153, in upscale_and_restore
    upscaled = upscaling.upscale_img(pil_img, pp_options)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions\sd-webui-faceswaplab\scripts\faceswaplab_postprocessing\upscaling.py", line 19, in upscale_img
    result_image = pp_options.upscaler.scaler.upscale(
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\upscaler.py", line 68, in upscale
    img = self.do_upscale(img, selected_model)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\esrgan_model.py", line 36, in do_upscale
    return esrgan_upscale(model, img)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\esrgan_model.py", line 57, in esrgan_upscale
    return upscale_with_model(
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\upscaler_utils.py", line 74, in upscale_with_model
    output = upscale_pil_patch(model, tile)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\upscaler_utils.py", line 48, in upscale_pil_patch
    return torch_bgr_to_pil_image(model(tensor))
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\spandrel\__helpers\model_descriptor.py", line 472, in __call__
    output = self._call_fn(self.model, image)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\spandrel\__helpers\model_descriptor.py", line 439, in <lambda>
    self._call_fn = call_fn or (lambda model, image: model(image))
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\spandrel\architectures\ESRGAN\arch\RRDB.py", line 142, in forward
    return self.model(x)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\extensions-builtin\Lora\networks.py", line 599, in network_Conv2d_forward
    return originals.Conv2d_forward(self, input)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\dml\amp\autocast_mode.py", line 43, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: forward(op, args, kwargs))
  File "C:\Users\mbord_\Documents\stable-diffusion-webui-directml\modules\dml\amp\autocast_mode.py", line 15, in forward
    return op(*args, **kwargs)
RuntimeError: Cannot set version_counter for inference tensor

**To Reproduce**
Venv built from scratch, clean install of A1111 and FaceSwap Lab.

**Expected behavior**
In inpaint tab of img2img, I usually set the attached options and it ran smoothly, producing swapped face. Now it's not possible to get an upscaled face.
![SRC](https://github.com/user-attachments/assets/0058b52c-0458-4bd5-9577-2db3eb8d443b)
![Zrzut ekranu 2024-09-04 220457](https://github.com/user-attachments/assets/006eaff4-e1db-45a0-b26a-d162ce73b7f0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome
 - Version Latest of all.

**Comment by Voidbord** [comment]
Ok, I think it's a problem of Directml - there has been an update recently.
