### ISSUE TITLE
what should I do? ->Older versions of gradio may not work  ( issubclass() arg 1 must be a class) ?

### ISSUE THREAD

**Issue by NongZen** [glucauze/sd-webui-faceswaplab#5]
Error executing callback ui_tabs_callback for C:\picture\Ai\app\stable-diffusion-webui\stable-diffusion-webui-9523\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py
Traceback (most recent call last):
  File "C:\picture\Ai\app\stable-diffusion-webui\stable-diffusion-webui-9523\modules\script_callbacks.py", line 134, in ui_tabs_callback
    res += c.callback() or []
  File "C:\picture\Ai\app\stable-diffusion-webui\stable-diffusion-webui-9523\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_tab.py", line 454, in on_ui_tabs
    tools_ui()
  File "C:\picture\Ai\app\stable-diffusion-webui\stable-diffusion-webui-9523\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_tab.py", line 433, in tools_ui
    extract_btn.click(
  File "C:\picture\Ai\app\stable-diffusion-webui\stable-diffusion-webui-9523\venv\lib\site-packages\gradio\events.py", line 132, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "C:\picture\Ai\app\stable-diffusion-webui\stable-diffusion-webui-9523\venv\lib\site-packages\gradio\blocks.py", line 217, in set_event_trigger
    check_function_inputs_match(fn, inputs, inputs_as_dict)
  File "C:\picture\Ai\app\stable-diffusion-webui\stable-diffusion-webui-9523\venv\lib\site-packages\gradio\utils.py", line 869, in check_function_inputs_match
    if not is_special_typed_parameter(name):
  File "C:\picture\Ai\app\stable-diffusion-webui\stable-diffusion-webui-9523\venv\lib\site-packages\gradio\utils.py", line 858, in is_special_typed_parameter
    is_event_data = issubclass(parameter_types.get(name, int), EventData)
TypeError: issubclass() arg 1 must be a class

**Comment by VitaliyS** [comment]
I got the same error. Could this be due to using an older version of A1111? My A1111 is from Apr, 26. All other extensions are disabled

**Comment by glucauze** [comment]
Yes this could be it. I am using a1111 1.5.1 right now. I'm not sure about older versions. In any case, it looks like a gradio problem.

**Comment by VitaliyS** [comment]
This happens immediately upon start. Faceswaplab can't create a tab. Everything else works
![image](https://github.com/glucauze/sd-webui-faceswaplab/assets/1282704/3f07a66a-73d7-4daf-99ac-89404e7f01a9)

**Comment by VitaliyS** [comment]
I tried downgrading and upgrading the Gradio version. It didn't help me

**Comment by glucauze** [comment]
Ok, i will try to investigate further. Thanks for trying.

Sometimes the problem comes from the ui-config.json file at the root of sd, which is not properly updated. In this case, you need to rename it  (and restart) so that it can be rebuilt and see if it works better.

**Comment by glucauze** [comment]
I don't think it comes from torch. But it could comes from gradio :/ Will see if next versions still has this problem.

**Comment by glucauze** [comment]
Thx for trying. What version of gradio is used in this version ?

**Comment by VitaliyS** [comment]
No, your version is 3.32, not 3.23 =)

Everything works, I have accordion in the other panels and section in settings. But I haven't tab

**Comment by VitaliyS** [comment]
Okay, I figured out why the gradio update didn't work. A1111 puts the old version on startup

Well, I will use it without the tab

**Comment by glucauze** [comment]
If gradio is really a problem, I could remove the type annotations. But it's a pain to degrade code quality because of that.

**Comment by VitaliyS** [comment]
I can remove the type annotations for me only. But I don't know what I need delete
I don't think it's worth changing the code to work with older versions of gradio

**Comment by glucauze** [comment]
If you have the time, you can give it a try. That way we'll know for sure.

In the file : 
https://github.com/glucauze/sd-webui-faceswaplab/blob/main/scripts/faceswaplab_ui/faceswaplab_tab.py

For each function, for example : 
```python
def extract_faces(
    files: List[gr.File],
    extract_path: Optional[str],
    *components: List[gr.components.Component],
) -> Optional[List[Image.Image]]:
```

You can remove the annotation types like this : 
```python
def extract_faces(
    files,
    extract_path,
    *components,
)
```

**Comment by VitaliyS** [comment]
Thank you. It works

**Comment by glucauze** [comment]
Thanks for your feedback

**Comment by willyelrey10** [comment]
Hello, could someone help me update Gradio? I have this problem. 
"  FaceSwapLab - WARNING - Errors may occur with gradio versions lower than 3.32.0. Your version : 3.23.0"
Error executing callback ui_tabs_callback for C:\Users\Usuario\Documents\Stablediffusion\stable-diffusion-webui-master\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py
Traceback (most recent call last):
  File "C:\Users\Usuario\Documents\Stablediffusion\stable-diffusion-webui-master\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "C:\Users\Usuario\Documents\Stablediffusion\stable-diffusion-webui-master\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_tab.py", line 424, in on_ui_tabs
    tools_ui()
  File "C:\Users\Usuario\Documents\Stablediffusion\stable-diffusion-webui-master\extensions\sd-webui-faceswaplab\scripts\faceswaplab_ui\faceswaplab_tab.py", line 398, in tools_ui
    generate_checkpoint_btn.click(
  File "C:\Users\Usuario\Documents\Stablediffusion\stable-diffusion-webui-master\venv\lib\site-packages\gradio\events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "C:\Users\Usuario\Documents\Stablediffusion\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 195, in set_event_trigger
    check_function_inputs_match(fn, inputs, inputs_as_dict)
  File "C:\Users\Usuario\Documents\Stablediffusion\stable-diffusion-webui-master\venv\lib\site-packages\gradio\utils.py", line 940, in check_function_inputs_match
    if not is_special_typed_parameter(name):
  File "C:\Users\Usuario\Documents\Stablediffusion\stable-diffusion-webui-master\venv\lib\site-packages\gradio\utils.py", line 929, in is_special_typed_parameter
    is_event_data = issubclass(parameter_types.get(name, int), EventData)
TypeError: issubclass() arg 1 must be a class

**Comment by VitaliyS** [comment]
> could someone help me update Gradio?

You can simply delete the gradio folders in the venv\Lib\site-packages directory and automatic1111 will download the required version. But if you are using an older version of automatic1111, the version of gradio may not change
