### ISSUE TITLE
Lot of errors...

### ISSUE THREAD

**Issue by ZeroCool22** [glucauze/sd-webui-faceswaplab#89]
`*** Error running install.py for extension C:\Users\ZeroCool22\Desktop\Auto Respaldo\extensions\sd-webui-faceswaplab.
*** Command: "C:\Users\ZeroCool22\Desktop\Auto Respaldo\venv\Scripts\python.exe" "C:\Users\ZeroCool22\Desktop\Auto Respaldo\extensions\sd-webui-faceswaplab\install.py"
*** Error code: 1
*** stdout: Faceswaplab : Use GPU requirements
*** Checking faceswaplab requirements
*** Install dill
*** Installing sd-webui-faceswaplab requirement: dill
*** Install onnxruntime-gpu>=1.15.0
*** Installing sd-webui-faceswaplab requirement: onnxruntime-gpu>=1.15.0
*** Couldn't install sd-webui-faceswaplab requirement: onnxruntime-gpu>=1.15.0.
*** Command: "C:\Users\ZeroCool22\Desktop\Auto Respaldo\venv\Scripts\python.exe" -m pip install onnxruntime-gpu>=1.15.0 --prefer-binary
*** Error code: 1
*** stderr: WARNING: Ignoring invalid distribution -rotobuf (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -pencv-python (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -pencv-python (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -pencv-python (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** ERROR: Could not install packages due to an OSError: [WinError 5] Acceso denegado: 'C:\\Users\\ZeroCool22\\Desktop\\Auto Respaldo\\venv\\Lib\\site-packages\\onnxruntime\\capi\\onnxruntime_providers_shared.dll'
*** Check the permissions.
***
*** WARNING: Ignoring invalid distribution -rotobuf (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -pencv-python (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -pencv-python (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -pencv-python (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
***
*** [notice] A new release of pip available: 22.2.1 -> 23.2.1
*** [notice] To update, run: C:\Users\ZeroCool22\Desktop\Auto Respaldo\venv\Scripts\python.exe -m pip install --upgrade pip
***
*** Warning: Failed to install onnxruntime-gpu>=1.15.0, faceswaplab may not work. Try to restart server or install dependencies manually.
***
*** stderr: Traceback (most recent call last):
***   File "C:\Users\ZeroCool22\Desktop\Auto Respaldo\extensions\sd-webui-faceswaplab\install.py", line 65, in <module>
***     check_time = timeit.timeit(check_install, number=1)
***   File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\timeit.py", line 234, in timeit
***     return Timer(stmt, setup, timer, globals).timeit(number)
***   File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\timeit.py", line 178, in timeit
***     timing = self.inner(it, self.timer)
***   File "<timeit-src>", line 6, in inner
***   File "C:\Users\ZeroCool22\Desktop\Auto Respaldo\extensions\sd-webui-faceswaplab\install.py", line 60, in check_install
***     raise e
***   File "C:\Users\ZeroCool22\Desktop\Auto Respaldo\extensions\sd-webui-faceswaplab\install.py", line 50, in check_install
***     launch.run_pip(
***   File "C:\Users\ZeroCool22\Desktop\Auto Respaldo\modules\launch_utils.py", line 130, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "C:\Users\ZeroCool22\Desktop\Auto Respaldo\modules\launch_utils.py", line 107, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install sd-webui-faceswaplab requirement: onnxruntime-gpu>=1.15.0.
*** Command: "C:\Users\ZeroCool22\Desktop\Auto Respaldo\venv\Scripts\python.exe" -m pip install onnxruntime-gpu>=1.15.0 --prefer-binary
*** Error code: 1
*** stderr: WARNING: Ignoring invalid distribution -rotobuf (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -pencv-python (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -pencv-python (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -pencv-python (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** ERROR: Could not install packages due to an OSError: [WinError 5] Acceso denegado: 'C:\\Users\\ZeroCool22\\Desktop\\Auto Respaldo\\venv\\Lib\\site-packages\\onnxruntime\\capi\\onnxruntime_providers_shared.dll'
*** Check the permissions.
***
*** WARNING: Ignoring invalid distribution -rotobuf (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -pencv-python (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -pencv-python (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -pencv-python (c:\users\zerocool22\desktop\auto respaldo\venv\lib\site-packages)
***
*** [notice] A new release of pip available: 22.2.1 -> 23.2.1
*** [notice] To update, run: C:\Users\ZeroCool22\Desktop\Auto Respaldo\venv\Scripts\python.exe -m pip install --upgrade pip
***`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win. 10 x64
 - Browser FireFox
 - Version 116.0.3

**Additional context**

**Comment by ZincStoat** [comment]
Installed this today and got the same startup error.
